### ISSUE TITLE
Issue with updating ADCIRC

### ISSUE THREAD

**Issue by uturuncoglu** [oceanmodeling/adcirc#4]
The ADCIRC is facing with netcdf error with the recent version of the ADCIRC. This is documented in the following issue - https://github.com/adcirc/adcirc/issues/417. Probably we need to regenerate netcdf input files.

**Comment by uturuncoglu** [comment]
@janahaddad I am not sure but is there anyone in the team that could work on it. If not I could try to find time to look at it. I think we need to build the recent version of ADCIRC and use the prep tools to generate input files. Then try to run the case again. I am not sure if anything else needs to be done.

**Comment by uturuncoglu** [comment]
@janahaddad I used following commands to create part of the files (for `coastal_ike_shinnecock_atm2adc`) but it is still falling. 

```
adcprep --np 11 --partmesh_npart
adcprep --np 11 --prepall
```
There could be other files that I don't know how i could produce.

**Comment by janahaddad** [comment]
@uturuncoglu thanks let's discuss on Monday

**Comment by janahaddad** [comment]
@uturuncoglu Guessing it's because this case is running with netcdf hotsart restart files (e.g. fort.67.nc or fort.68.nc) and those need to be regenerated also. Would it make sense to first try running without the restart file to see if that succeeds?  That would be setting `IHOT` parameter to 0 in fort.15 input file (and I guess changing a restart parameter in UFS configure?) 

Anyway we can discuss on Monday and I will do a bit more digging before then

**Comment by uturuncoglu** [comment]
@janahaddad JFYI, I ask to ADCIRC developers about the restart file and they point me the repository that has files for another case. https://github.com/adcirc/adcirc-testsuite/tree/main/adcirc/adcirc_quarterannular-2d-netcdf-hotstart/01_cs/control So, maybe we could use the old restart file and using structure of the new file (incl. metadata) to generate new file for our RT. I also saw couple of new variables that is not available in the old file but I'll check them and maybe could find then in other files that I regenerated with the new version of adcirj prep. I also ask Takis about the source of the restart file.

**Comment by janahaddad** [comment]
Ok, I'd suppose it's easier to just re-run the model setup that was used to generate the hotstart/restart files for coastal-app test suite... there is no clear information that I can see about that, but maybe it's described in this bash script: https://github.com/noaa-ocs-modeling/CoastalApp-testsuite/blob/main/ike_shinnecock.atm2adc/functions_testcase 

It looks like that script asks user to choose either "spinup" or "run". The hotsart files should be generated in a spinup run

But aside from this... I still think as we discussed Monday it's better to stick with the version of adcirc that is working now, and in the future stay with the version used for NOS STOFS-2D-Global system so that we can have access to NOS power-users of ADCIRC that way

**Comment by janahaddad** [comment]
@uturuncoglu can close based on recent discussions/decisions?

**Comment by uturuncoglu** [comment]
@janahaddad Okay. I am closing this now.
